---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wapy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: wapy-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://wapy:{{ .WAPY_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/wapy?sslmode=require"
        EMAIL_SERVER_USER: "{{ .EMAIL_SERVER_USER }}"
        EMAIL_SERVER_PASSWORD: "{{ .EMAIL_SERVER_PASSWORD }}"
        EMAIL_SERVER_HOST: "{{ .EMAIL_SERVER_HOST }}"
        EMAIL_SERVER_PORT: "{{ .EMAIL_SERVER_PORT }}"
        EMAIL_FROM: "{{ .EMAIL_FROM }}"
        EMAIL_CONTACT_EMAIL: "{{ .EMAIL_CONTACT_EMAIL }}"
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        SUBSCRIPTION_JWT_SECRET: "{{ .SUBSCRIPTION_JWT_SECRET }}"
        SITE_URL: "https://wapy.${SECRET_DOMAIN}"
        DISABLE_USER_REGISTRATION: "{{ .DISABLE_USER_REGISTRATION }}"
  dataFrom:
    - extract:
        key: wapy
