---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./egress.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./probe.yaml
  - ./prometheusrule.yaml
  - ./scrapeconfig.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: seedbox-dashboard
    files:
      - seedbox.json=./dashboards/seedbox.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    # This keeps Grafana's ${DS_PROMETHEUS} and $__rate_interval macros from being blanked.
    kustomize.toolkit.fluxcd.io/substitute: disabled
