{
 "title": "SABnzbd",
 "tags": [
  "sabnzbd",
  "exportarr",
  "media",
  "downloads"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "sabnzbd_instance",
    "label": "SABnzbd Instance",
    "query": {
     "query": "label_values({__name__=~\"sabnzbd_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 15, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sabnzbd_downloaded_bytes{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Lifetime"
    },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range]))",
     "legendFormat": "Recent"
    },
    {
     "expr": "sabnzbd_queue_length{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sabnzbd_total_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "sabnzbd_remaining_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    },
    {
     "expr": "sum(sabnzbd_server_articles_success{instance=~\"${sabnzbd_instance}\"}) / sum(sabnzbd_server_articles_total{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "x": 15, "y": 0, "w": 5, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_quota_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "1 - max(sabnzbd_remaining_quota_bytes{instance=~\"${sabnzbd_instance}\"} / sabnzbd_quota_bytes{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sabnzbd_remaining_quota_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_article_cache_articles{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Articles"
    },
    {
     "expr": "sabnzbd_article_cache_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Exporter Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$sabnzbd_instance\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "x": 3, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_status{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Mode"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_time_estimate_seconds{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Time Remaining"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "x": 9, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_speed_bps{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "D/L Speed"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 2, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_paused_all{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Hard Pause"
    }
   ]
  },
  {
   "title": "Pause Duration",
   "type": "stat",
   "gridPos": { "x": 14, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_pause_duration_seconds{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Resume In"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "bargauge",
   "gridPos": { "x": 17, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sabnzbd_disk_used_bytes{instance=~\"${sabnzbd_instance}\",folder=\"download\"} / sabnzbd_disk_total_bytes{instance=~\"${sabnzbd_instance}\",folder=\"download\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "min(sabnzbd_disk_used_bytes{instance=~\"${sabnzbd_instance}\",folder=\"complete\"} / sabnzbd_disk_total_bytes{instance=~\"${sabnzbd_instance}\",folder=\"complete\"})",
     "legendFormat": "Complete"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lifetime Downloads By Server",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 16, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Downloaded By Server",
   "type": "bargauge",
   "gridPos": { "x": 8, "y": 16, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Download Percent",
   "type": "piechart",
   "gridPos": { "x": 16, "y": 16, "w": 8, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}