---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domainlocker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: domainlocker-secret
    template:
      engineVersion: v2
      data:
        DL_PG_NAME: domain_locker
        DL_PG_USER: domain_locker
        DL_PG_PASSWORD: "{{ .DOMAINLOCKER_POSTGRES_PASS }}"
        DL_PG_HOST: postgres18-rw.database.svc.cluster.local
        DL_PG_PORT: "5432"
  dataFrom:
    - extract:
        key: domainlocker
