{
 "title": "VMware VM",
 "description": "VMware ESXi single instance graphs.",
 "tags": [ "vmware" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "vm", "label": "vm", "query": "label_values(vm_name)" }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(vmware_vm_boot_timestamp_seconds{vm_name=~\"$vm\"}) ",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(vmware_vm_boot_timestamp_seconds{vm_name=~\"$vm\"}) ",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "VM Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_vm_template{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=~\"$vm\"}==1"
    }
   ]
  },
  {
   "title": "Tools Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_vm_guest_tools_running_status{vm_name=~\"$vm\"})",
     "legendFormat": "{{ tools_status }}"
    }
   ]
  },
  {
   "title": "Tools Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(vmware_vm_guest_tools_version{vm_name=~\"$vm\"})",
     "legendFormat": "{{ tools_version}}"
    }
   ]
  },
  {
   "title": "Cpu Number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_vm_num_cpu{vm_name=~\"$vm\"}) "
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100"
    }
   ]
  },
  {
   "title": "VM Cpu Ready",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "(vmware_vm_cpu_ready_summation{vm_name=~\"$vm\"})/200"
    }
   ]
  },
  {
   "title": "VM Cpu Co-Stop",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "targets": [
    {
     "expr": "vmware_vm_cpu_costop_summation{vm_name=~\"$vm\"}/200"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_vm_memory_max{vm_name=~\"$vm\"})  "
    }
   ]
  },
  {
   "title": "VM Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vmware_vm_mem_usage_average{vm_name=~\"$vm\"}) * 100 / (vmware_vm_memory_max{vm_name=~\"$vm\"})"
    }
   ]
  },
  {
   "title": "VM Ballooning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "vmware_vm_mem_vmmemctl_average{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM Swapped",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100",
     "legendFormat": "Cpu Usage"
    },
    {
     "expr": "vmware_vm_cpu_demand_average{vm_name=~\"$vm\"}/vmware_vm_max_cpu_usage{vm_name=~\"$vm\"}*100",
     "legendFormat": "Cpu Demand"
    }
   ]
  },
  {
   "title": "VM CPU Contention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_vm_cpu_ready_summation{vm_name=~\"$vm\"})/200",
     "legendFormat": "Cpu Ready"
    },
    {
     "expr": "vmware_vm_cpu_costop_summation{vm_name=~\"$vm\"}/200",
     "legendFormat": "Co-Stop"
    }
   ]
  },
  {
   "title": "VM Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_vm_mem_usage_average{vm_name=~\"$vm\"}) * 100 / (vmware_vm_memory_max{vm_name=~\"$vm\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "VM Memory Contention",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_mem_vmmemctl_average{vm_name=~\"$vm\"}",
     "legendFormat": "Ballooning"
    },
    {
     "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "VM Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_received_average{vm_name=~\"$vm\"}+vmware_vm_net_transmitted_average{vm_name=~\"$vm\"}",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=~\"$vm\"}",
     "legendFormat": "Read Usage"
    },
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=~\"$vm\"}",
     "legendFormat": "Transmit Usage"
    },
    {
     "expr": "vmware_vm_net_broadcastTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Broadcast TX"
    },
    {
     "expr": "vmware_vm_net_broadcastRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Broadcast RX"
    },
    {
     "expr": "vmware_vm_net_multicastTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Multicast TX"
    },
    {
     "expr": "vmware_vm_net_multicastRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Multicast RX"
    }
   ]
  },
  {
   "title": "VM Network Packet Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_droppedTx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Packet Dropped TX"
    },
    {
     "expr": "vmware_vm_net_droppedRx_summation{vm_name=~\"$vm\"}",
     "legendFormat": "Packet Dropped RX"
    }
   ]
  },
  {
   "title": "VM Disk Read And Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=~\"$vm\"}+vmware_vm_disk_write_average{vm_name=~\"$vm\"}",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "vmware_vm_disk_read_average{vm_name=~\"$vm\"}",
     "legendFormat": "Read Usage"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=~\"$vm\"}",
     "legendFormat": "Write Usage"
    }
   ]
  },
  {
   "title": "VM Disk Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_maxTotalLatency_latest{vm_name=~\"$vm\"}",
     "legendFormat": "Disk Latency"
    }
   ]
  }
 ]
}