---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# TODO: add a palworld-exporter sidecar once the world has save data (bostrt/palworld-exporter).
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palworld
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: palworld
  values:
    controllers:
      palworld:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: thijsvanloef/palworld-server-docker
              tag: v2.8.0@sha256:a308e2eaa494f2df0448a59cb22f820ba679bd57729880528c48981a49c08870
            env:
              TZ: "${TIMEZONE}"
              PUID: "1000"
              PGID: "1000"
              PORT: &port 8211
              PLAYERS: "16"
              MULTITHREADING: "true"
              COMMUNITY: "false"
              SERVER_NAME: "Palworld Server"
              SERVER_DESCRIPTION: "Private Palworld Server"
              RCON_ENABLED: "true"
              RCON_PORT: &rcon-port 25575
              UPDATE_ON_BOOT: "true"
              DEATH_PENALTY: "None"
            envFrom:
              - secretRef:
                  name: palworld-secret
            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 1000m
              limits:
                memory: 16Gi
    service:
      app:
        controller: palworld
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${SVC_PALWORLD_ADDR}"
        ports:
          game:
            protocol: UDP
            port: *port
          rcon:
            port: *rcon-port
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: palworld
        globalMounts:
          - path: /palworld
