---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backup.yaml
  - ./coder.yaml
  - ./domainlocker.yaml
  - ./domainwatchdog.yaml
  - ./guacamole.yaml
  - ./keeper.yaml
  - ./litellm.yaml
  - ./mailarchiver.yaml
  - ./metabase.yaml
  - ./miniflux.yaml
  - ./netbox.yaml
  - ./paperless.yaml
  - ./pocketid.yaml
  - ./prowler.yaml
  - ./reactiveresume.yaml
  - ./romm.yaml
  - ./scanopy.yaml
  - ./tandoor.yaml
  - ./tracearr.yaml
  - ./wapy.yaml
  - ./warracker.yaml
