---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./domainlocker.yaml
  - ./domainwatchdog.yaml
  - ./mailarchiver.yaml
  - ./metabase.yaml
  - ./miniflux.yaml
  - ./reactiveresume.yaml
  - ./romm.yaml
  - ./tandoor.yaml
  - ./tracearr.yaml
  - ./wapy.yaml
  - ./warracker.yaml
