---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  interval: 1h
  chart:
    spec:
      chart: netdata
      version: 3.7.157
      sourceRef:
        kind: HelmRepository
        name: netdata
      interval: 1h
  values:
    image:
      repository: netdata/netdata
      tag: v2.8.4

    ingress:
      enabled: false

    parent:
      enabled: true
      alarms:
        storageclass: ceph-block
        volumesize: 2Gi
      database:
        storageclass: ceph-block
        volumesize: 20Gi
      configs:
        netdata:
          enabled: true
          path: /etc/netdata/netdata.conf
          data: |
            [db]
              mode = dbengine
              dbengine tier 0 retention size = 10GiB
              dbengine tier 1 retention size = 5GiB
              dbengine tier 2 retention size = 2GiB

    child:
      enabled: true

    k8sState:
      enabled: true
