---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metabase
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
