---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secret
    template:
      engineVersion: v2
      data:
        KONFLATE_PUSH_TOKEN: "{{ .KONFLATE_PUSH_TOKEN }}"
  dataFrom:
    - extract:
        key: konflate
