---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        UI_USERNAME: "{{ .LITELLM_UI_USERNAME }}"
        UI_PASSWORD: "{{ .LITELLM_UI_PASSWORD }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        DATABASE_URL: "postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/litellm?sslmode=require"
        REDIS_PASSWORD: "{{ .DRAGONFLY_PASSWORD }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: cloudnative-pg
    - extract:
        key: dragonfly
