---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        LITELLM_SALT_KEY: "{{ .LITELLM_SALT_KEY }}"
        UI_USERNAME: "{{ .LITELLM_UI_USERNAME }}"
        UI_PASSWORD: "{{ .LITELLM_UI_PASSWORD }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        DATABASE_URL: "postgresql://{{ .LITELLM_POSTGRES_USER }}:{{ .LITELLM_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/litellm?sslmode=require"
        INIT_POSTGRES_DBNAME: litellm
        INIT_POSTGRES_HOST: postgres18-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LITELLM_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LITELLM_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: cloudnative-pg
