---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deduparr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: deduparr
  values:
    controllers:
      deduparr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/kernald/deduparr
              tag: 1.1.0@sha256:c3a3182edd8bc8381b689ada87b8ff3acdb0e11253be9d578fed633d52be9ad7
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: deduparr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ready
                    port: &port 9090
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: deduparr
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: deduparr
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config-file:
        type: configMap
        name: deduparr-configmap
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
