---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      whodb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/clidey/whodb
              tag: 0.122.0@sha256:61159d9089222b3c725037cf543a462a3c859eb50fd14dfceab7a30dbac45229
            envFrom:
              - secretRef:
                  name: whodb
            resources:
              requests:
                cpu: 30m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: whodb
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
