---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app whodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      whodb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/clidey/whodb
              tag: 0.101.0@sha256:0319d7b8b35f439f430b9f673fefdb70c63f79bf313d23991e13d67ed7a59607
            envFrom:
              - secretRef:
                  name: whodb
            resources:
              requests:
                cpu: 30m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: whodb
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
