---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./allow-same-namespace.yaml
  - ./allow-all-egress.yaml
  - ./allow-prometheus-scraping.yaml
  - ./allow-kube-apiserver.yaml
