---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: romm-secret
    template:
      engineVersion: v2
      data:
        ROMM_DB_DRIVER: postgresql
        DB_HOST: postgres18-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: romm
        DB_PASSWD: "{{ .ROMM_POSTGRES_PASSWORD }}"
        DB_NAME: romm
        IGDB_CLIENT_ID: "{{ .IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .IGDB_CLIENT_SECRET }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        STEAMGRIDDB_API_KEY: "{{ .STEAMGRIDDB_API_KEY }}"
  dataFrom:
    - extract:
        key: romm
    - extract:
        key: igdb
    - extract:
        key: steamgriddb
