---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: guacamole-secret
    template:
      engineVersion: v2
      data:
        OPENID_CLIENT_ID: "{{ .GUACAMOLE_CLIENT_ID }}"
        POSTGRESQL_HOSTNAME: postgres18-rw.database.svc.cluster.local
        POSTGRESQL_PORT: "5432"
        POSTGRESQL_DATABASE: guacamole
        POSTGRESQL_USER: guacamole
        POSTGRESQL_PASSWORD: "{{ .GUACAMOLE_POSTGRES_PASSWORD }}"
        POSTGRESQL_SSL_MODE: require
        DATABASE_URL: "postgres://guacamole:{{ .GUACAMOLE_POSTGRES_PASSWORD }}@postgres18-rw.database.svc.cluster.local:5432/guacamole?sslmode=require"
  dataFrom:
    - extract:
        key: guacamole
