---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailarchiver
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mailarchiver-secret
    template:
      engineVersion: v2
      data:
        Authentication__Username: "{{ .MAILARCHIVER_USERNAME }}"
        Authentication__Password: "{{ .MAILARCHIVER_PASSWORD }}"
        MAILARCHIVER_POSTGRES_DB: mailarchiver
        MAILARCHIVER_POSTGRES_USER: mailarchiver
        MAILARCHIVER_POSTGRES_PASSWORD: "{{ .MAILARCHIVER_POSTGRES_PASSWORD }}"
        ConnectionStrings__DefaultConnection: "Host=postgres18-rw.database.svc.cluster.local;Port=5432;Database=mailarchiver;Username=mailarchiver;Password={{ .MAILARCHIVER_POSTGRES_PASSWORD }};SslMode=Require"
  dataFrom:
    - extract:
        key: mailarchiver
