---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: wallos
  values:
    controllers:
      wallos:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 5.8.2@sha256:14a1255d806c2f1e03317a7d98fce5ac58ea2437aae0b66234aae7b53751edf9
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: wallos
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      db:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/html/db
            subPath: db
          - path: /var/www/html/images/uploads/logos
            subPath: logos
