---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tracearr-secret
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        REDIS_URL: "redis://default:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379"
        DATABASE_URL: "postgres://tracearr:{{ .TRACEARR_POSTGRES_PASS }}@tracearr-postgres-rw.media.svc.cluster.local:5432/tracearr?sslmode=no-verify"
  dataFrom:
    - extract:
        key: tracearr
    - extract:
        key: dragonfly
