---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-secret
    template:
      engineVersion: v2
      data:
        CODER_PG_CONNECTION_URL: "postgres://coder:{{ .CODER_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/coder?sslmode=require"
  dataFrom:
    - extract:
        key: coder
