---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager
  values:
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
      - --dns01-recursive-nameservers-only
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 256Mi
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 128Mi
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
