---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: examprep
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: examprep
  values:
    controllers:
      examprep:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lukeevanstech/examprep
              tag: 0.1.0@sha256:0d6579f6448cd49b0e9a64f2f29faa7ccf331a6cab8ed02113aabec17a1d420f
            env:
              TZ: ${TIMEZONE}
              APP_URL: https://examprep.${SECRET_DOMAIN}
              OIDC_ISSUER: https://id.${SECRET_DOMAIN}
              OIDC_NAME: Pocket ID
            envFrom:
              - secretRef:
                  name: examprep-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 8080
                  periodSeconds: 30
                  timeoutSeconds: 3
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 96Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: examprep
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
