---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: grafana
  namespace: ai
spec:
  proxyRef: litellm
  url: http://mcp-grafana-proxy.ai.svc.cluster.local:8080/mcp
