---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxidized
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oxidized-secret
    template:
      engineVersion: v2
      data:
        OPNSENSE_USERNAME: "{{ .OPNSENSE_USERNAME }}"
        OPNSENSE_PASSWORD: "{{ .OPNSENSE_PASSWORD }}"
        ONYX_USERNAME: "{{ .ONYX_USERNAME }}"
        ONYX_PASSWORD: "{{ .ONYX_PASSWORD }}"
        MIKROTIK_POE_USERNAME: "{{ .MIKROTIK_POE_USERNAME }}"
        MIKROTIK_POE_PASSWORD: "{{ .MIKROTIK_POE_PASSWORD }}"
        MIKROTIK_NONPOE_USERNAME: "{{ .MIKROTIK_NONPOE_USERNAME }}"
        MIKROTIK_NONPOE_PASSWORD: "{{ .MIKROTIK_NONPOE_PASSWORD }}"
        RUCKUS_USERNAME: "{{ .RUCKUS_USERNAME }}"
        RUCKUS_PASSWORD: "{{ .RUCKUS_PASSWORD }}"
        GITHUB_DEPLOY_KEY: "{{ .GITHUB_DEPLOY_KEY }}"
        GITHUB_KNOWN_HOSTS: "{{ .GITHUB_KNOWN_HOSTS }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: oxidized
