---
apiVersion: v1alpha1
kind: ImageVerificationConfig
rules:
  - imagePatterns:
      - "ghcr.io/siderolabs/*"
    policy:
      sigstore:
        keyless:
          identities:
            - issuer: "https://token.actions.githubusercontent.com"
              subjectRegExp: "^https://github\\.com/siderolabs/[^/]+/\\.github/workflows/[^/]+@refs/(tags/v[0-9].+|heads/release-[0-9].+)$"
