---
# ZFS ARC deliberately uses all available RAM and releases it under memory pressure.
apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: zfs-storage-memory
spec:
  matchers:
    - name: alertname
      value: NodeMemoryHighUtilization
      isRegex: false
      isEqual: true
    - name: instance
      value: ${SECRET_STORAGE_SERVER}:9100
      isRegex: false
      isEqual: true
