---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcp-searxng
spec:
  chartRef:
    kind: OCIRepository
    name: mcp-searxng
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
    controllers:
      mcp-searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/isokoliuk/mcp-searxng
              tag: 1.8.0@sha256:e19e276f50123dfaae990bb31a8ae62930ee466b716d70ddc16b9842b0327979
            env:
              SEARXNG_URL: http://searxng.default.svc.cluster.local:8080
              MCP_HTTP_PORT: &port 3000
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
