---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: burrito-system
components:
  - ../../components/global-vars
resources:
  - ./namespace.yaml
  - ./burrito/ks.yaml
  - ./layers/ks.yaml
