---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smokeping
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: smokeping
  values:
    controllers:
      smokeping:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/library/alpine
              tag: 3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
            command:
              - "/bin/sh"
              - "-c"
            args:
              - "cp /configmap/* /config"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/smokeping
              tag: 2.9.0@sha256:ebfbbc32a51612de154b6c0c105836ae40905411cbac43592257afce727c0534
            env:
              TZ: ${TIMEZONE}
              PUID: "1000"
              PGID: "1000"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 192Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: smokeping
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        type: emptyDir
      data:
        existingClaim: "{{ .Release.Name }}"
      configmap:
        type: configMap
        name: smokeping-configmap
