---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keeper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: keeper-secret
    template:
      engineVersion: v2
      data:
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DATABASE_URL: "postgres://keeper:{{ .KEEPER_POSTGRES_PASS }}@postgres18-rw.database.svc.cluster.local:5432/keeper?sslmode=disable"
        REDIS_URL: "redis://default:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379"
  dataFrom:
    - extract:
        key: keeper
    - extract:
        key: dragonfly
