---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pocket-id-secret
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        POSTGRES_DB: "pocketid"
        POSTGRES_HOST: postgres18-rw.database.svc.cluster.local
        POSTGRES_USER: pocketid
        POSTGRES_PASSWORD: "{{ .POCKET_ID_DBPASS }}"
        DB_CONNECTION_STRING: "postgresql://pocketid:{{ .POCKET_ID_DBPASS }}@postgres18-rw.database.svc.cluster.local:5432/pocketid?sslmode=require"
  dataFrom:
    - extract:
        key: maxmind
    - extract:
        key: pocket-id
