---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    template:
      engineVersion: v2
      data:
        WEBSOCKET_REDIS_URL: "redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/0"
  dataFrom:
    - extract:
        key: dragonfly
